// Code generated by ent, DO NOT EDIT.

package userfollow

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/k0kishima/golang-realworld-example-app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldLTE(FieldID, id))
}

// FollowerID applies equality check predicate on the "follower_id" field. It's identical to FollowerIDEQ.
func FollowerID(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldEQ(FieldFollowerID, v))
}

// FolloweeID applies equality check predicate on the "followee_id" field. It's identical to FolloweeIDEQ.
func FolloweeID(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldEQ(FieldFolloweeID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldEQ(FieldCreatedAt, v))
}

// FollowerIDEQ applies the EQ predicate on the "follower_id" field.
func FollowerIDEQ(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldEQ(FieldFollowerID, v))
}

// FollowerIDNEQ applies the NEQ predicate on the "follower_id" field.
func FollowerIDNEQ(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldNEQ(FieldFollowerID, v))
}

// FollowerIDIn applies the In predicate on the "follower_id" field.
func FollowerIDIn(vs ...uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldIn(FieldFollowerID, vs...))
}

// FollowerIDNotIn applies the NotIn predicate on the "follower_id" field.
func FollowerIDNotIn(vs ...uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldNotIn(FieldFollowerID, vs...))
}

// FollowerIDGT applies the GT predicate on the "follower_id" field.
func FollowerIDGT(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldGT(FieldFollowerID, v))
}

// FollowerIDGTE applies the GTE predicate on the "follower_id" field.
func FollowerIDGTE(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldGTE(FieldFollowerID, v))
}

// FollowerIDLT applies the LT predicate on the "follower_id" field.
func FollowerIDLT(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldLT(FieldFollowerID, v))
}

// FollowerIDLTE applies the LTE predicate on the "follower_id" field.
func FollowerIDLTE(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldLTE(FieldFollowerID, v))
}

// FolloweeIDEQ applies the EQ predicate on the "followee_id" field.
func FolloweeIDEQ(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldEQ(FieldFolloweeID, v))
}

// FolloweeIDNEQ applies the NEQ predicate on the "followee_id" field.
func FolloweeIDNEQ(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldNEQ(FieldFolloweeID, v))
}

// FolloweeIDIn applies the In predicate on the "followee_id" field.
func FolloweeIDIn(vs ...uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldIn(FieldFolloweeID, vs...))
}

// FolloweeIDNotIn applies the NotIn predicate on the "followee_id" field.
func FolloweeIDNotIn(vs ...uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldNotIn(FieldFolloweeID, vs...))
}

// FolloweeIDGT applies the GT predicate on the "followee_id" field.
func FolloweeIDGT(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldGT(FieldFolloweeID, v))
}

// FolloweeIDGTE applies the GTE predicate on the "followee_id" field.
func FolloweeIDGTE(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldGTE(FieldFolloweeID, v))
}

// FolloweeIDLT applies the LT predicate on the "followee_id" field.
func FolloweeIDLT(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldLT(FieldFolloweeID, v))
}

// FolloweeIDLTE applies the LTE predicate on the "followee_id" field.
func FolloweeIDLTE(v uuid.UUID) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldLTE(FieldFolloweeID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserFollow {
	return predicate.UserFollow(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserFollow) predicate.UserFollow {
	return predicate.UserFollow(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserFollow) predicate.UserFollow {
	return predicate.UserFollow(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserFollow) predicate.UserFollow {
	return predicate.UserFollow(sql.NotPredicates(p))
}
