#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
if [ -z "$STAGED_GO_FILES" ]; then
  echo "No Go files staged, skipping goimports and golint."
  exit 0
fi

echo "Running goimports..."
goimports -w $STAGED_GO_FILES
git add $STAGED_GO_FILES

echo "Pre-commit checks passed."
