// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/k0kishima/golang-realworld-example-app/ent/predicate"
	"github.com/k0kishima/golang-realworld-example-app/ent/userfollow"
)

// UserFollowDelete is the builder for deleting a UserFollow entity.
type UserFollowDelete struct {
	config
	hooks    []Hook
	mutation *UserFollowMutation
}

// Where appends a list predicates to the UserFollowDelete builder.
func (ufd *UserFollowDelete) Where(ps ...predicate.UserFollow) *UserFollowDelete {
	ufd.mutation.Where(ps...)
	return ufd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ufd *UserFollowDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ufd.sqlExec, ufd.mutation, ufd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ufd *UserFollowDelete) ExecX(ctx context.Context) int {
	n, err := ufd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ufd *UserFollowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userfollow.Table, sqlgraph.NewFieldSpec(userfollow.FieldID, field.TypeUUID))
	if ps := ufd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ufd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ufd.mutation.done = true
	return affected, err
}

// UserFollowDeleteOne is the builder for deleting a single UserFollow entity.
type UserFollowDeleteOne struct {
	ufd *UserFollowDelete
}

// Where appends a list predicates to the UserFollowDelete builder.
func (ufdo *UserFollowDeleteOne) Where(ps ...predicate.UserFollow) *UserFollowDeleteOne {
	ufdo.ufd.mutation.Where(ps...)
	return ufdo
}

// Exec executes the deletion query.
func (ufdo *UserFollowDeleteOne) Exec(ctx context.Context) error {
	n, err := ufdo.ufd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userfollow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ufdo *UserFollowDeleteOne) ExecX(ctx context.Context) {
	if err := ufdo.Exec(ctx); err != nil {
		panic(err)
	}
}
