// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserFollow is the predicate function for userfollow builders.
type UserFollow func(*sql.Selector)
